using System.Collections.Generic;

namespace TypeMaster.Services;

/// <summary>
/// 打字小游戏词库。
///
/// 来源：google-10000-english-no-swears（Google Web Trillion Word Corpus，按词频降序）。
/// 处理：按字母数分三档，并过滤缩写、技术网络词、品牌机构名、地名人名日期、
///       敏感消极词，以及元音占比过低 / 含长辅音簇的非自然词。
/// 每档只保留词频最高的前若干个，避免长尾生僻词影响游戏体验。
///
/// 与 <c>TypingGameEngine.MaxWordLength</c> 配合：
/// 简单档 3-5 字母 / 普通档 6-8 字母 / 困难档 9+ 字母。
///
/// 词量（旧版仅 66 个词，反复抽必然重复）：
/// 简单 1500 / 普通 2000 / 困难 1200，合计 4700。
/// </summary>
public static class GameWords
{
    /// <summary>简单档：3-5 字母，共 1500 词（按词频降序，越靠前越常用）。</summary>
    private static readonly string[] EasyWords =
    {
        "the", "and", "for", "that", "this", "with", "you", "not", "are", "from",
        "your", "all", "have", "new", "more", "was", "will", "home", "can", "about",
        "page", "has", "free", "but", "our", "one", "other", "time", "they", "site",
        "may", "what", "their", "news", "out", "use", "any", "there", "see", "only",
        "his", "when", "here", "who", "web", "also", "now", "help", "get", "view",
        "been", "would", "how", "were", "some", "these", "its", "like", "than", "find",
        "price", "date", "back", "top", "had", "list", "name", "just", "over", "state",
        "year", "day", "into", "email", "two", "next", "used", "work", "last", "most",
        "music", "buy", "data", "make", "them", "post", "her", "city", "add", "such",
        "after", "best", "then", "good", "video", "well", "where", "books", "high", "each",
        "she", "years", "order", "very", "book", "items", "read", "group", "need", "many",
        "user", "said", "does", "set", "under", "mail", "full", "map", "life", "know",
        "games", "way", "days", "part", "could", "great", "hotel", "real", "item", "must",
        "store", "made", "off", "line", "did", "send", "type", "local", "those", "using",
        "car", "take", "area", "want", "phone", "forum", "long", "based", "code", "show",
        "even", "index", "being", "women", "much", "sign", "file", "link", "open", "today",
        "south", "case", "same", "pages", "own", "found", "house", "both", "photo", "game",
        "power", "while", "care", "down", "three", "total", "place", "end", "him", "big",
        "media", "law", "water", "size", "art", "since", "guide", "shop", "board", "white",
        "text", "rate", "times", "sites", "level", "form", "love", "old", "john", "main",
        "call", "hours", "image", "title", "money", "every", "visit", "save", "tools", "low",
        "value", "york", "man", "card", "jobs", "food", "learn", "sale", "job", "teen",
        "room", "too", "point", "join", "men", "west", "sales", "look", "left", "team",
        "box", "week", "note", "live", "large", "table", "model", "air", "plan", "human",
        "yes", "hot", "cost", "movie", "say", "going", "test", "come", "cart", "again",
        "play", "never", "users", "topic", "tax", "below", "less", "got", "blog", "login",
        "let", "legal", "above", "park", "side", "act", "red", "give", "quote", "sell",
        "rates", "key", "body", "young", "field", "few", "east", "paper", "age", "club",
        "road", "gift", "hard", "pay", "four", "issue", "range", "audio", "write", "offer",
        "blue", "easy", "given", "files", "event", "china", "needs", "yet", "major", "star",
        "areas", "space", "hand", "sun", "keep", "enter", "share", "added", "baby", "run",
        "term", "film", "put", "head", "radio", "until", "cell", "color", "self", "away",
        "once", "least", "log", "sure", "trade", "cars", "tell", "able", "david", "fun",
        "green", "close", "drive", "gold", "arts", "lot", "ask", "means", "daily", "beach",
        "past", "due", "five", "upon", "says", "land", "done", "ever", "early", "miles",
        "sound", "ago", "word", "bill", "talk", "rules", "final", "adult", "cheap", "kids",
        "true", "else", "mark", "rock", "tips", "plus", "auto", "cover", "edit", "fast",
        "fact", "unit", "tech", "meet", "far", "often", "feel", "bank", "risk", "deals",
        "james", "town", "heart", "error", "girl", "toys", "clear", "golf", "makes", "loan",
        "wide", "india", "taken", "sort", "half", "cases", "step", "quick", "none", "paul",
        "lake", "whole", "later", "basic", "fire", "chat", "along", "among", "speed", "loss",
        "face", "oil", "bit", "base", "near", "japan", "doing", "loans", "shoes", "stay",
        "turn", "mean", "notes", "king", "copy", "pics", "force", "cash", "bay", "river",
        "seen", "port", "album", "stop", "bar", "views", "dog", "build", "soon", "lines",
        "held", "asked", "mind", "lost", "tour", "menu", "hope", "wish", "role", "weeks",
        "came", "lower", "union", "names", "hour", "six", "leave", "teens", "huge", "woman",
        "kind", "move", "cable", "logo", "nice", "score", "sent", "band", "lead", "went",
        "mode", "ideas", "fund", "allow", "homes", "super", "male", "took", "asian", "cause",
        "song", "cnet", "focus", "late", "fall", "idea", "rooms", "win", "tool", "voice",
        "bed", "comes", "hill", "maps", "deal", "hold", "safe", "prior", "ready", "feed",
        "round", "sea", "built", "blood", "hall", "earth", "ship", "paid", "italy", "hair",
        "basis", "award", "tree", "peter", "thus", "wall", "extra", "rated", "quite", "boy",
        "horse", "vote", "owner", "ways", "son", "rule", "takes", "told", "input", "feet",
        "agent", "valid", "door", "trial", "units", "cool", "wrote", "metal", "asia", "uses",
        "java", "guest", "seems", "pass", "multi", "fees", "skin", "prev", "mary", "ring",
        "grade", "panel", "floor", "iraq", "boys", "deep", "rest", "hit", "pool", "mini",
        "fish", "eye", "sense", "pack", "stage", "goods", "born", "race", "maybe", "spain",
        "youth", "core", "break", "sets", "dance", "wood", "fee", "rent", "dark", "apple",
        "enjoy", "aid", "host", "isbn", "fair", "civil", "steel", "fixed", "ohio", "gets",
        "mike", "trip", "eyes", "farm", "peace", "coast", "lord", "agree", "hear", "goes",
        "fan", "wife", "ten", "hits", "zone", "cat", "jack", "flat", "flow", "scale",
        "frame", "path", "chief", "gives", "laws", "pet", "heard", "begin", "royal", "clean",
        "guy", "cup", "suite", "vegas", "skip", "diet", "gear", "lots", "piece", "sheet",
        "firm", "seven", "older", "jump", "looks", "whose", "ball", "goal", "sold", "wind",
        "lives", "palm", "stone", "pain", "xbox", "buyer", "steve", "oral", "edge", "root",
        "pink", "shot", "label", "waste", "cold", "chair", "phase", "bag", "motor", "foot",
        "mass", "count", "claim", "heat", "wild", "miss", "task", "bug", "santa", "mid",
        "soft", "alone", "jones", "fuel", "walk", "wait", "rose", "joint", "pick", "dates",
        "upper", "prime", "limit", "began", "louis", "creek", "urban", "tours", "load", "labor",
        "admin", "tags", "heavy", "guys", "drop", "solid", "theme", "rich", "ipod", "seem",
        "touch", "goals", "hire", "serve", "magic", "mount", "gave", "ones", "latin", "avoid",
        "rank", "kong", "faith", "chain", "moved", "reach", "inch", "lab", "gamma", "snow",
        "camp", "fill", "owned", "equal", "gone", "codes", "teams", "fort", "tried", "disc",
        "boat", "named", "laser", "icon", "ends", "taxes", "mouse", "brain", "dream", "false",
        "cast", "felt", "soul", "flag", "hello", "atom", "brief", "ended", "eight", "iron",
        "void", "alert", "disk", "queen", "fix", "sweet", "desk", "dave", "diego", "hong",
        "vice", "votes", "duty", "bear", "gain", "ocean", "lack", "iowa", "train", "knew",
        "feeds", "route", "zoom", "blow", "anime", "speak", "query", "clip", "wire", "rural",
        "tape", "judge", "acid", "cent", "null", "zero", "filed", "roll", "korea", "bath",
        "leads", "font", "beta", "fail", "brian", "jazz", "bags", "miami", "wear", "wales",
        "minor", "noted", "mom", "rare", "davis", "bars", "dual", "rise", "sleep", "bird",
        "scene", "lady", "fans", "eat", "seat", "aim", "bids", "toll", "cape", "tip",
        "mine", "guess", "whom", "ski", "math", "dogs", "ahead", "moon", "devel", "delta",
        "fear", "wars", "cisco", "kept", "alpha", "bonus", "beat", "arms", "tea", "trees",
        "utah", "hide", "refer", "babes", "toy", "layer", "slow", "hip", "faqs", "nine",
        "eric", "spot", "grow", "dot", "ratio", "rain", "onto", "proof", "diff", "bass",
        "hole", "pets", "ride", "maine", "pair", "ideal", "cream", "runs", "yeah", "boxes",
        "evil", "aware", "shape", "irish", "euro", "usage", "cap", "ink", "mixed", "peak",
        "exist", "wheel", "salt", "angel", "bell", "noise", "array", "pin", "greek", "jeff",
        "lane", "occur", "coach", "kevin", "ages", "plug", "cook", "hat", "perl", "bike",
        "plate", "lose", "seek", "tony", "kits", "logic", "soil", "wet", "matt", "fox",
        "sizes", "plain", "exit", "iran", "keys", "wave", "costa", "acts", "mesh", "trail",
        "dean", "setup", "poll", "unix", "bond", "blues", "scope", "bears", "jean", "hop",
        "visa", "mouth", "meter", "pure", "fruit", "lens", "draw", "warm", "lewis", "babe",
        "sugar", "crew", "legs", "allen", "genre", "slide", "rear", "exact", "bound", "node",
        "lock", "micro", "mile", "mens", "bowl", "tank", "kid", "paint", "delay", "pilot",
        "novel", "ultra", "idaho", "dish", "slot", "lodge", "gray", "broad", "demo", "sarah",
        "hate", "rice", "loop", "foods", "guard", "raise", "gary", "vary", "arab", "milk",
        "drama", "boot", "audit", "push", "tower", "yours", "misc", "alan", "jason", "dear",
        "solar", "jose", "jane", "doubt", "earn", "doors", "twin", "dont", "bruce", "bits",
        "twice", "suit", "chip", "sit", "simon", "loved", "char", "saved", "moore", "treat",
        "piano", "echo", "grid", "voip", "teach", "rapid", "pull", "hairy", "boots", "pulse",
        "metro", "pearl", "nick", "plot", "anne", "heads", "exam", "logos", "ryan", "beds",
        "grey", "bold", "opera", "asset", "scan", "humor", "aged", "lived", "bulk", "pmid",
        "cute", "para", "meant", "plane", "seed", "meets", "peer", "tampa", "meat", "grace",
        "susan", "adams", "bang", "villa", "bone", "bugs", "inner", "gate", "roman", "tone",
        "busy", "neck", "wing", "taste", "tiny", "rail", "sides", "tube", "belt", "lease",
        "proud", "giant", "seats", "alarm", "usual", "angle", "honor", "eagle", "nurse", "quiet",
        "luck", "dial", "comic", "maker", "gang", "smoke", "cake", "apart", "semi", "coins",
        "cafe", "till", "pen", "epson", "shoe", "sand", "joy", "actor", "seal", "prize",
        "lies", "pipe", "deck", "wayne", "alive", "prove", "thin", "ridge", "modem", "sick",
        "dose", "lets", "moves", "cats", "rhode", "greg", "worse", "boats", "fiber", "folk",
        "okay", "roger", "hist", "lift", "inter", "grove", "mall", "dad", "roads", "fell",
        "yard", "faces", "mayor", "sean", "yield", "pour", "tion", "dust", "hence", "radar",
        "lakes", "diary", "kent", "adds", "ear", "baker", "ebony", "tie", "ward", "roof",
        "kiss", "beast", "dodge", "pizza", "rush", "mpeg", "yoga", "woods", "lamp", "rico",
        "phil", "jokes", "twiki", "glad", "wins", "globe", "rack", "dicke", "boss", "pride",
        "keith", "linda", "ross", "chile", "anna", "solo", "maria", "tall", "plaza", "pdas",
        "quest", "toe", "nova", "booty", "acres", "venue", "vital", "excel", "modes", "wake",
        "enemy", "opens", "drum", "iraqi", "vista", "flood", "foto", "ease", "arena", "tabs",
        "smile", "armed", "pine", "tend", "gulf", "rick", "laura", "tiger", "hunt", "thai",
        "fred", "boost", "mill", "icons", "moral", "keeps", "pound", "burn", "roses", "bread",
        "tough", "solve", "sole", "tones", "laid", "clay", "weak", "wise", "odds", "marc",
        "reads", "roles", "sons", "leaf", "pad", "saudi", "fault", "cuba", "silk", "kate",
        "karen", "wolf", "fluid", "fits", "kick", "meal", "hurt", "pot", "slip", "marie",
        "kenya", "cuts", "mars", "sized", "manga", "egg", "caps", "pill", "meta", "dated",
        "shoot", "mint", "elite", "spin", "poems", "robot", "wash", "gnome", "roots", "noble",
        "shore", "loves", "loose", "aims", "soap", "axis", "genes", "hero", "punk", "duke",
        "pace", "wage", "atlas", "dawn", "feels", "carl", "coat", "rica", "liver", "decor",
        "doll", "peru", "evans", "fails", "aging", "nike", "reed", "mice", "intro", "vast",
        "jeans", "wrap", "mood", "favor", "quiz", "sigma", "beam", "tops", "aside", "essay",
        "trace", "shut", "ncaa", "thou", "mask", "coal", "zoo", "spoke", "arrow", "rough",
        "weird", "fotos", "outer", "crop", "tales", "nodes", "seeds", "cited", "lite", "tired",
        "steam", "acute", "stood", "sing", "tons", "carol", "hang",

    };

    /// <summary>普通档：6-8 字母，共 2000 词（按词频降序，越靠前越常用）。</summary>
    private static readonly string[] NormalWords =
    {
        "search", "contact", "business", "online", "services", "service", "people", "health", "products", "should",
        "product", "policy", "number", "please", "support", "message", "public", "school", "through", "review",
        "privacy", "company", "general", "research", "reviews", "program", "united", "center", "travel", "comments",
        "report", "member", "details", "before", "hotels", "because", "results", "office", "national", "design",
        "posted", "internet", "address", "within", "states", "shipping", "reserved", "subject", "between", "family",
        "special", "prices", "project", "version", "section", "related", "security", "county", "american", "members",
        "network", "computer", "download", "without", "access", "current", "control", "history", "pictures", "personal",
        "location", "change", "rating", "children", "during", "return", "students", "shopping", "account", "digital",
        "profile", "previous", "events", "another", "property", "quality", "listing", "content", "country", "private",
        "little", "customer", "compare", "movies", "include", "college", "article", "provide", "source", "author",
        "around", "course", "canada", "process", "training", "credit", "science", "advanced", "english", "estate",
        "select", "photos", "thread", "category", "gallery", "register", "however", "market", "library", "really",
        "action", "series", "features", "industry", "provided", "required", "second", "forums", "better", "medical",
        "friend", "articles", "feedback", "looking", "issues", "complete", "street", "comment", "working", "against",
        "standard", "person", "mobile", "payment", "student", "programs", "offers", "recent", "stores", "problem",
        "memory", "social", "language", "options", "create", "america", "single", "example", "password", "latest",
        "question", "changes", "status", "browse", "building", "seller", "always", "result", "groups", "release",
        "analysis", "request", "making", "picture", "possible", "future", "problems", "meeting", "become", "interest",
        "similar", "garden", "schools", "million", "listed", "learning", "energy", "delivery", "popular", "stories",
        "journal", "reports", "welcome", "central", "images", "notice", "original", "council", "includes", "archive",
        "others", "format", "society", "safety", "friends", "edition", "messages", "further", "updated", "having",
        "provides", "already", "studies", "common", "specific", "several", "living", "called", "display", "limited",
        "powered", "director", "natural", "whether", "period", "planning", "official", "weather", "average", "window",
        "france", "region", "island", "record", "direct", "records", "district", "calendar", "update", "resource",
        "present", "either", "document", "material", "written", "hosting", "tickets", "centre", "finance", "minutes",
        "europe", "reading", "topics", "usually", "together", "videos", "percent", "function", "getting", "global",
        "economic", "player", "projects", "submit", "germany", "amount", "included", "though", "various", "weight",
        "received", "choose", "archives", "points", "magazine", "camera", "receive", "domain", "methods", "chapter",
        "policies", "beauty", "manager", "position", "listings", "models", "michael", "simple", "wireless", "license",
        "annual", "method", "purchase", "active", "response", "practice", "figure", "holiday", "enough", "designed",
        "writing", "discount", "higher", "effects", "created", "remember", "yellow", "increase", "kingdom", "thought",
        "storage", "nature", "orders", "africa", "summary", "agency", "european", "activity", "although", "western",
        "income", "overall", "package", "contents", "players", "engine", "regional", "supplies", "started", "double",
        "screen", "exchange", "continue", "across", "benefits", "needed", "season", "someone", "anything", "printer",
        "believe", "effect", "volume", "anyone", "mortgage", "silver", "inside", "solution", "mature", "rather",
        "addition", "nothing", "certain", "running", "jewelry", "clothing", "robert", "homepage", "islands", "advice",
        "career", "rental", "decision", "british", "sellers", "middle", "taking", "values", "division", "coming",
        "object", "machine", "actually", "client", "returns", "capital", "follow", "sample", "england", "culture",
        "george", "choice", "starting", "courses", "consumer", "airport", "foreign", "artist", "outside", "levels",
        "channel", "letter", "phones", "summer", "degree", "contract", "button", "releases", "matter", "custom",
        "almost", "located", "multiple", "editor", "featured", "female", "thomas", "primary", "numbers", "reason",
        "browser", "answer", "friendly", "schedule", "purpose", "feature", "police", "everyone", "approach", "cameras",
        "physical", "medicine", "ratings", "chicago", "wanted", "unique", "survey", "animal", "sources", "mexico",
        "regular", "secure", "evidence", "station", "paypal", "favorite", "option", "master", "valley", "recently",
        "probably", "rentals", "improve", "larger", "networks", "parents", "impact", "transfer", "kitchen", "carolina",
        "wedding", "ground", "overview", "owners", "perfect", "classic", "command", "cities", "william", "express",
        "distance", "ensure", "involved", "partners", "budget", "guides", "success", "maximum", "existing", "selected",
        "patients", "warning", "forward", "flowers", "retail", "animals", "useful", "directly", "housing", "catalog",
        "searches", "mother", "traffic", "joined", "strategy", "modern", "senior", "ireland", "teaching", "testing",
        "charge", "instead", "canadian", "normal", "entire", "leading", "positive", "fitness", "chinese", "opinion",
        "football", "output", "greater", "likely", "develop", "artists", "contains", "session", "republic", "vacation",
        "century", "academic", "graphics", "indian", "expected", "dating", "pacific", "mountain", "filter", "mailing",
        "vehicle", "longer", "consider", "northern", "behind", "german", "buying", "proposed", "default", "require",
        "outdoor", "morning", "allows", "protein", "reported", "partner", "authors", "boards", "faculty", "parties",
        "mission", "modified", "released", "internal", "unless", "richard", "detailed", "japanese", "approved", "target",
        "except", "ability", "moving", "places", "southern", "yourself", "winter", "battery", "pressure", "boston",
        "keywords", "medium", "purposes", "itself", "defined", "papers", "playing", "awards", "studio", "reader",
        "virtual", "device", "answers", "remote", "external", "offered", "theory", "remove", "surface", "minimum",
        "visual", "variety", "teachers", "martin", "manual", "subjects", "agents", "repair", "finally", "updates",
        "desktop", "classes", "sector", "capacity", "requires", "jersey", "father", "electric", "quotes", "officer",
        "driver", "respect", "unknown", "teacher", "workers", "georgia", "campus", "showing", "creative", "benefit",
        "progress", "funding", "devices", "fiction", "watches", "careers", "beyond", "families", "museum", "accepted",
        "former", "complex", "agencies", "parent", "spanish", "setting", "economy", "highest", "helpful", "critical",
        "musical", "angeles", "employee", "bottom", "packages", "detail", "changed", "colorado", "russian", "largest",
        "african", "titles", "relevant", "justice", "connect", "basket", "applied", "weekly", "demand", "square",
        "advance", "auction", "allowed", "correct", "charles", "nation", "selling", "elements", "species", "module",
        "resort", "facility", "random", "pricing", "minister", "motion", "fashion", "visitors", "monitor", "trading",
        "forest", "coverage", "couple", "giving", "chance", "vision", "ending", "clients", "actions", "listen",
        "discuss", "accept", "clinical", "sciences", "markets", "lowest", "appear", "currency", "leather", "patient",
        "actual", "commerce", "perhaps", "persons", "village", "accounts", "amateur", "factors", "coffee", "settings",
        "cultural", "easily", "poster", "closed", "holidays", "zealand", "balance", "graduate", "replies", "initial",
        "thinking", "league", "minute", "provider", "optional", "sections", "fishing", "effort", "fields", "fantasy",
        "letters", "context", "install", "apparel", "johnson", "quickly", "dollars", "driving", "measures", "kansas",
        "chemical", "doctor", "reduce", "brought", "himself", "enable", "exercise", "leader", "diamond", "israel",
        "servers", "meetings", "seconds", "arizona", "keyword", "username", "produced", "italian", "pocket", "freedom",
        "argument", "creating", "premium", "upgrade", "factor", "growing", "stream", "hearing", "eastern", "auctions",
        "therapy", "entries", "signed", "serious", "errors", "efforts", "informed", "worked", "quantity", "sorted",
        "platform", "nursing", "defense", "machines", "covered", "recovery", "merchant", "expert", "protect", "became",
        "orange", "vehicles", "prevent", "campaign", "marine", "guitar", "finding", "examples", "saying", "claims",
        "affairs", "intended", "towards", "suggest", "charges", "reasons", "talking", "manage", "corner", "oregon",
        "element", "requests", "separate", "quarter", "tables", "define", "racing", "column", "identify", "avenue",
        "missing", "domestic", "sitemap", "houston", "viewed", "moment", "extended", "sequence", "centers", "opening",
        "reserve", "recipes", "plastic", "produce", "placed", "counter", "failure", "follows", "weekend", "dollar",
        "ontario", "bridge", "native", "williams", "movement", "printing", "baseball", "approval", "played", "contacts",
        "readers", "jackson", "matching", "offering", "profit", "leaders", "posters", "variable", "expect", "parking",
        "compared", "russia", "seattle", "golden", "lighting", "forces", "brother", "turned", "portable", "returned",
        "pattern", "theatre", "earlier", "sponsor", "warranty", "indiana", "objects", "delete", "evening", "assembly",
        "nuclear", "signal", "issued", "sexual", "powerful", "obtained", "flower", "passed", "supplied", "opinions",
        "promote", "stated", "hawaii", "appears", "decided", "covers", "designs", "maintain", "tourism", "priority",
        "adults", "savings", "graphic", "payments", "binding", "winning", "straight", "served", "prepared", "dining",
        "atlanta", "dakota", "credits", "clearly", "handle", "criteria", "pubmed", "behavior", "enlarge", "revenue",
        "measure", "changing", "looked", "festival", "experts", "whatever", "logged", "laptop", "vintage", "exactly",
        "explore", "maryland", "concept", "nearly", "eligible", "checkout", "reality", "forgot", "handling", "origin",
        "gaming", "billion", "scotland", "faster", "dallas", "bought", "nations", "followed", "broken", "alaska",
        "equity", "speech", "shared", "sounds", "forced", "height", "speaker", "obtain", "offices", "designer",
        "remain", "managed", "failed", "marriage", "secret", "negative", "austin", "theater", "missouri", "andrew",
        "perform", "healthy", "assets", "injury", "joseph", "ministry", "drivers", "figures", "married", "proposal",
        "sharing", "portal", "waiting", "gratis", "banking", "toward", "assist", "conduct", "calling", "serving",
        "profiles", "comics", "matters", "houses", "postal", "controls", "breaking", "combined", "ultimate", "finish",
        "reduced", "extreme", "samples", "daniel", "reviewed", "forecast", "removed", "singles", "amounts", "contain",
        "accuracy", "pharmacy", "brazil", "creation", "static", "hunter", "famous", "writer", "chairman", "oklahoma",
        "speakers", "academy", "dynamic", "gender", "cleaning", "concerns", "colour", "vendor", "officers", "referred",
        "supports", "regions", "junior", "meaning", "ladies", "ticket", "agreed", "soccer", "import", "posting",
        "presence", "instant", "viewing", "majority", "aspects", "austria", "scheme", "utility", "preview", "manner",
        "matrix", "despite", "turkey", "proper", "degrees", "seeking", "inches", "phoenix", "shares", "daughter",
        "standing", "comfort", "colors", "ordering", "appeal", "cruise", "bookmark", "specials", "disney", "becomes",
        "drives", "alabama", "improved", "achieve", "dealer", "nearby", "carried", "happen", "exposure", "miller",
        "outdoors", "clothes", "caused", "luxury", "frames", "indeed", "circuit", "printed", "removal", "easier",
        "printers", "adding", "kentucky", "taylor", "factory", "interior", "revised", "optical", "relative", "amazing",
        "identity", "suites", "feeling", "hidden", "victoria", "serial", "relief", "revision", "planet", "copies",
        "recipe", "permit", "seeing", "tennis", "bedroom", "instance", "licensed", "orlando", "bureau", "recorded",
        "pieces", "finished", "dinner", "lawyers", "discover", "patterns", "fourth", "advisor", "stations", "remains",
        "greatest", "operator", "generic", "census", "transit", "compact", "poetry", "tracking", "keeping", "attempt",
        "matches", "engines", "forget", "accurate", "stephen", "climate", "managing", "sister", "walking", "explain",
        "smaller", "newest", "happened", "extent", "lesbians", "export", "managers", "aircraft", "modules", "sweden",
        "conflict", "versions", "employer", "describe", "concern", "backup", "citizens", "heritage", "holding", "trouble",
        "spread", "expand", "audience", "assigned", "jordan", "affect", "virgin", "raised", "directed", "dealers",
        "sporting", "helping", "affected", "totally", "expenses", "indicate", "blonde", "anderson", "organic", "albums",
        "cheats", "guests", "hosted", "nevada", "thailand", "agenda", "anyway", "advisory", "template", "prince",
        "circle", "anywhere", "atlantic", "edward", "investor", "leaving", "wildlife", "cooking", "speaking", "sponsors",
        "respond", "entered", "launch", "checking", "belgium", "guidance", "highway", "observed", "booking", "glossary",
        "fiscal", "denver", "filled", "channels", "appendix", "notify", "portion", "supplier", "cables", "cotton",
        "biology", "dental", "border", "ancient", "debate", "causes", "arkansas", "leisure", "learned", "notebook",
        "explorer", "historic", "attached", "opened", "husband", "upcoming", "britain", "concert", "scores", "comedy",
        "adopted", "weblog", "linear", "carrier", "edited", "constant", "linked", "portland", "concepts", "reflect",
        "deliver", "wonder", "lessons", "begins", "reform", "alerts", "treated", "relating", "assume", "alliance",
        "confirm", "neither", "howard", "offline", "leaves", "engineer", "replace", "reached", "becoming", "safari",
        "relation", "enabled", "montana", "tested", "enhance", "adapter", "formal", "hockey", "colleges", "laptops",
        "showed", "editors", "threads", "supreme", "brothers", "presents", "estimate", "cancel", "limits", "outlet",
        "winner", "episode", "potter", "bulletin", "modify", "epinions", "painting", "universe", "patent", "eating",
        "planned", "watching", "mirror", "sterling", "sessions", "buyers", "journals", "jennifer", "antonio", "charged",
        "taiwan", "chosen", "greece", "labour", "terminal", "behalf", "liquid", "nebraska", "salary", "gourmet",
        "properly", "orleans", "saving", "empire", "resume", "prepare", "avatar", "hundreds", "helped", "premier",
        "tomorrow", "decide", "consent", "visiting", "downtown", "keyboard", "contest", "suitable", "millions", "chamber",
        "guinea", "findings", "muscle", "clicking", "typical", "chicken", "attend", "shower", "sending", "tonight",
        "holdem", "province", "governor", "seemed", "swimming", "spyware", "formula", "pakistan", "reliable", "finder",
        "unable", "periods", "attacks", "resorts", "biggest", "memorial", "visitor", "insert", "gateway", "alumni",
        "drawing", "ordered", "fighting", "happens", "romance", "themes", "powers", "pregnant", "focused", "bargain",
        "cellular", "norway", "vermont", "asking", "normally", "hunting", "diabetes", "bodies", "cutting", "writers",
        "flexible", "mapping", "numerous", "indexed", "superior", "paying", "cartoon", "granted", "choices", "carbon",
        "spending", "magnetic", "registry", "crisis", "outlook", "massive", "denmark", "employed", "header", "formed",
        "sheets", "patrick", "puerto", "displays", "plasma", "allowing", "earnings", "journey", "delaware", "bidding",
        "banner", "charter", "barbara", "counties", "dreams", "blogger", "occurred", "reverse", "deposit", "seminar",
        "latina", "wheels", "specify", "formats", "depends", "concrete", "editing", "poland", "folder", "womens",
        "upload", "voting", "notices", "detroit", "resident", "possibly", "airline", "regard", "exists", "smooth",
        "strike", "flashing", "narrow", "threat", "surveys", "sitting", "putting", "vietnam", "trailer", "castle",
        "gardens", "missed", "malaysia", "antique", "labels", "willing", "acting", "stored", "antiques", "density",
        "hundred", "strange", "mention", "parallel", "amended", "operate", "bathroom", "stable", "doctors", "lesson",
        "cinema", "drinking", "reaction", "enhanced", "entitled", "severe", "generate", "deluxe", "monitors", "duration",
        "pursuant", "fabric", "visits", "domains", "contrast", "adoption", "capture", "pounds", "buffalo", "desire",
        "camping", "welfare", "caught", "marked", "driven", "measured", "medline", "bottle", "marshall", "massage",
        "rubber", "closing", "thousand", "legend", "monster", "columns", "hamilton", "cookies", "tutorial", "entity",
        "cruises", "holder", "portugal", "lawrence", "duties", "valuable", "ethics", "forever", "dragon", "captain",
        "imagine", "heating", "stereo", "dealing", "commit", "airlines", "liberal", "livecam", "jacket", "oracle",
        "matthew", "aviation", "hobbies", "excess", "console", "commands", "achieved", "injuries", "shipped", "voltage",
        "anthony", "nintendo", "loading", "appeared", "franklin", "mining", "ongoing", "imaging", "liberty", "wyoming",
        "convert", "analyst", "garage", "exciting", "ringtone", "finland", "morgan", "derived", "pleasure", "oriented",
        "desktops", "columbus", "postage", "producer", "cheese", "semester", "applies", "casinos", "apache", "filters",
        "fellow", "lounge", "hilton", "proteins", "horror", "familiar", "capable", "douglas", "debian", "elected",
        "carrying", "victory", "madison", "editions", "mainly", "ethnic", "citizen", "vertical", "occurs", "absolute",
        "consists", "anytime", "guardian", "lecture", "layout", "classics", "horses", "donate", "taught", "worker",
        "breaks", "genetic", "waters", "promise", "prefer", "cabinet", "harris", "bringing", "evaluate", "tiffany",
        "tropical", "collect", "streets", "vector", "shaved", "turning", "buffer", "purple", "mutual", "pipeline",
        "chairs", "everyday", "inquiry", "ethernet", "checked", "exhibit", "sierra", "visible", "desert", "oldest",
        "mercury", "steven", "handbook", "navigate", "summit", "spaces", "burning", "escape", "coupons", "somewhat",
        "receiver", "glance", "scottish", "arcade", "richmond", "russell", "obvious", "covering", "platinum", "judgment",
        "bedrooms", "filing", "foster", "modeling", "passing", "awarded", "trials", "tissue", "masters", "alberta",
        "commons", "spectrum", "arrival", "pottery", "emphasis", "aspect", "awesome", "mexican", "counts", "priced",
        "desired", "closer", "assumes", "shadow", "riding", "firefox", "expense", "venture", "clinic", "korean",
        "healing", "princess", "entering", "packet", "studios", "buttons", "funded", "thompson", "winners", "extend",
        "dublin", "rolling", "memories", "nelson", "arrived", "creates", "tourist", "adequate", "senator", "grades",
        "cartoons", "digest", "lodging", "entirely", "replaced", "rescue", "losses", "reducing", "stopped", "closely",
        "shooting", "launched", "abroad", "arthur", "visited", "walker", "suggests", "operated", "targets", "overseas",
        "counsel", "invited", "gordon", "farmers", "queries", "ukraine", "absence", "nearest", "cluster", "vendors",
        "whereas", "serves", "surprise", "partial", "shoppers", "couples", "ranking", "simpson", "sublime", "palace",
        "verify", "trusted", "copper", "receipt", "supposed", "ordinary", "nobody", "applying", "knowing", "reporter",
        "champion", "cloudy", "sentence", "throat", "ignore", "uniform", "wealth", "vacuum", "dancing", "writes",
        "outcomes", "survival", "publish", "jonathan", "whenever", "lifetime", "pioneer", "acrobat", "plates", "athletic",
        "thermal", "essays", "telling", "fairly", "coastal", "config", "charity", "campbell", "harbor", "hungary",
        "traveler", "segment", "realize", "puzzle", "rising", "aluminum", "wishlist", "insight", "secrets", "latter",
        "trailers", "repeat", "syndrome", "glasses", "enables", "builder", "jessica", "pupils", "stewart", "outcome",
        "expanded", "casual", "polish", "lovely", "extras", "centres", "clause", "indoor", "bulgaria", "broker",
        "charger", "believed", "cooling", "divorce", "shopper", "donald", "sensor", "exposed", "telecom", "angels",
        "deputy", "sealed", "loaded", "scenes", "spanking", "founded", "chronic", "catering", "finger", "locate",
        "trained", "wooden", "motors", "roberts", "incident", "dynamics", "decrease", "pension", "revenues", "emerging",
        "herself", "churches", "reserves", "minority", "diverse", "recorder", "facing", "passion", "defence", "patches",
        "refund", "divided", "emails", "insider", "seminars", "makers", "hearts", "carter", "legacy", "pleased",
        "danger", "vitamin", "widely", "phrase", "genuine", "raising", "paradise", "bigger", "billing", "diesel",
        "versus", "combine", "exceed", "babies", "compiled", "romantic", "revealed", "albert", "examine", "graham",
        "bristol", "margaret", "compaq", "portions", "infant", "sectors", "samuel", "grounds", "regards", "unlike",
        "equation", "baskets", "proven", "cached", "warren", "studied", "reviewer", "involves", "profits", "florist",
        "webcam", "earrings", "enjoyed", "chapters", "francis", "noticed", "socket", "silent", "literary", "signals",
        "humans", "analog", "facial", "choosing", "talent", "seeker", "wisdom", "boundary", "packard", "offset",
        "payday", "philip", "holders", "believes", "swedish", "deadline", "witness", "collins", "equipped", "stages",
        "powder", "broadway", "acquired", "assess", "stones", "entrance", "losing", "gadgets", "glasgow", "impacts",
        "induced", "linking", "appeals", "earned", "illness", "pending", "parker", "lebanon", "teenage", "triple",
        "cooper", "vincent", "secured", "unusual", "answered", "disorder", "routine", "toolbar", "titans", "wearing",
        "sought", "mounted", "habitat", "firewall", "median", "scanner", "herein", "animated", "judicial", "bachelor",
        "actors", "liable", "brochure", "morris", "petition", "eminem", "recall", "antenna", "picked", "assumed",
        "belief", "bikini", "memphis", "shoulder", "lookup", "brokers", "diameter", "ottawa", "podcast", "seasons",
    };

    /// <summary>困难档：9+ 字母，共 1200 词（按词频降序，越靠前越常用）。</summary>
    private static readonly string[] HardWords =
    {
        "information", "available", "university", "management", "international", "development", "education", "community", "technology", "following",
        "resources", "including", "directory", "department", "description", "insurance", "different", "categories", "conditions", "accessories",
        "questions", "application", "financial", "equipment", "performance", "experience", "important", "activities", "additional", "something",
        "professional", "committee", "washington", "reference", "companies", "computers", "australia", "discussion", "entertainment", "agreement",
        "marketing", "association", "collection", "solutions", "electronics", "technical", "microsoft", "conference", "environment", "statement",
        "downloads", "applications", "requirements", "individual", "everything", "production", "commercial", "advertising", "treatment", "newsletter",
        "knowledge", "registered", "protection", "engineering", "published", "corporate", "customers", "materials", "countries", "advertise",
        "environmental", "availability", "employment", "commission", "administration", "institute", "sponsored", "electronic", "condition", "effective",
        "organization", "selection", "corporation", "executive", "necessary", "according", "particular", "facilities", "opportunities", "appropriate",
        "statistics", "investment", "registration", "furniture", "structure", "distribution", "industrial", "potential", "responsible", "communications",
        "associated", "foundation", "documents", "communication", "independent", "operating", "developed", "telephone", "population", "navigation",
        "operations", "therefore", "understand", "publications", "connection", "publisher", "introduction", "properties", "accommodation", "excellent",
        "opportunity", "assessment", "especially", "interface", "operation", "restaurants", "beautiful", "locations", "significant", "technologies",
        "manufacturer", "providing", "authority", "considered", "programme", "enterprise", "educational", "employees", "alternative", "processing",
        "responsibility", "resolution", "publication", "relations", "photography", "components", "assistance", "completed", "organizations", "otherwise",
        "transportation", "disclaimer", "membership", "recommended", "character", "maintenance", "functions", "trademarks", "phentermine", "submitted",
        "television", "interested", "throughout", "established", "programming", "regarding", "increased", "understanding", "beginning", "associates",
        "businesses", "specified", "restaurant", "procedures", "relationship", "traditional", "sometimes", "themselves", "interesting", "evaluation",
        "implementation", "galleries", "references", "presented", "literature", "respective", "definition", "secretary", "networking", "australian",
        "magazines", "francisco", "individuals", "guidelines", "installation", "described", "attention", "difference", "regulations", "certificate",
        "directions", "documentation", "automotive", "successful", "communities", "situation", "publishing", "developing", "determine", "temperature",
        "announcements", "historical", "ringtones", "difficult", "scientific", "satellite", "particularly", "functional", "monitoring", "architecture",
        "recommend", "dictionary", "accounting", "manufacturing", "professor", "generally", "continued", "techniques", "permission", "generation",
        "component", "guarantee", "processes", "interests", "paperback", "classifieds", "supported", "competition", "providers", "characters",
        "thousands", "apartments", "generated", "administrative", "practices", "reporting", "essential", "affiliate", "immediately", "designated",
        "integrated", "configuration", "comprehensive", "universal", "presentation", "languages", "compliance", "improvement", "pennsylvania", "challenge",
        "acceptance", "strategies", "affiliates", "multimedia", "certified", "computing", "interactive", "procedure", "leadership", "breakfast",
        "developer", "approximately", "recommendations", "comparison", "automatically", "minnesota", "adventure", "institutions", "assistant", "advertisement",
        "headlines", "yesterday", "determined", "wholesale", "extension", "statements", "completely", "electrical", "applicable", "manufacturers",
        "classical", "dedicated", "direction", "basketball", "wisconsin", "personnel", "identified", "professionals", "advantage", "newsletters",
        "estimated", "anonymous", "miscellaneous", "integration", "interview", "framework", "installed", "associate", "frequently", "discussions",
        "laboratory", "destination", "intelligence", "specifications", "tripadvisor", "residential", "decisions", "industries", "partnership", "editorial",
        "expression", "provisions", "principles", "suggestions", "replacement", "strategic", "economics", "compatible", "apartment", "netherlands",
        "consulting", "recreation", "participants", "favorites", "translation", "estimates", "protected", "philadelphia", "officials", "contained",
        "legislation", "parameters", "relationships", "tennessee", "representative", "frequency", "introduced", "departments", "residents", "displayed",
        "performed", "administrator", "addresses", "permanent", "agriculture", "constitutes", "portfolio", "practical", "delivered", "collectibles",
        "infrastructure", "exclusive", "originally", "utilities", "philosophy", "regulation", "reduction", "nutrition", "recording", "secondary",
        "wonderful", "announced", "prevention", "mentioned", "automatic", "maintained", "increasing", "connected", "directors", "participation",
        "containing", "combination", "amendment", "guaranteed", "libraries", "distributed", "singapore", "enterprises", "convention", "principal",
        "certification", "previously", "buildings", "household", "batteries", "positions", "contemporary", "permalink", "signature", "provision",
        "certainly", "newspaper", "liability", "trademark", "americans", "promotion", "conversion", "reasonable", "broadband", "influence",
        "importance", "prescription", "specifically", "represent", "conservation", "louisiana", "marketplace", "evolution", "certificates", "objectives",
        "suggested", "concerned", "structures", "encyclopedia", "continuing", "interracial", "competitive", "suppliers", "preparation", "receiving",
        "accordance", "discussed", "elizabeth", "reservations", "playstation", "annotation", "differences", "establish", "expressed", "paragraph",
        "mathematics", "compensation", "conducted", "percentage", "mississippi", "requested", "connecticut", "personals", "immediate", "agricultural",
        "supporting", "collections", "participate", "specialist", "experienced", "investigation", "institution", "searching", "proceedings", "favourite",
        "transmission", "characteristics", "experiences", "extremely", "verzeichnis", "concerning", "developers", "equivalent", "neighborhood", "variables",
        "continues", "curriculum", "responses", "circumstances", "identification", "appliances", "elementary", "unlimited", "printable", "enforcement",
        "hardcover", "celebrity", "chocolate", "bluetooth", "controlled", "requirement", "authorities", "representatives", "biography", "attractions",
        "transactions", "authorized", "retirement", "financing", "efficiency", "efficient", "commitment", "specialty", "interviews", "qualified",
        "discovery", "classified", "confidence", "lifestyle", "consistent", "clearance", "connections", "inventory", "converter", "organisation",
        "objective", "indicated", "securities", "volunteer", "democratic", "switzerland", "parameter", "processor", "dimensions", "contribute",
        "challenges", "recognition", "submission", "encourage", "regulatory", "inspection", "consumers", "territory", "transaction", "manchester",
        "contributions", "continuous", "resulting", "cambridge", "initiative", "execution", "increases", "contractor", "examination", "indicates",
        "committed", "extensive", "affordable", "candidate", "databases", "outstanding", "perspective", "messenger", "tournament", "consideration",
        "discounts", "catalogue", "publishers", "caribbean", "reservation", "remaining", "depending", "expansion", "purchased", "performing",
        "collected", "absolutely", "featuring", "implement", "scheduled", "calculator", "significantly", "temporary", "sufficient", "awareness",
        "vancouver", "contribution", "measurement", "constitution", "packaging", "consultation", "classroom", "democracy", "wallpaper", "merchandise",
        "resistance", "baltimore", "candidates", "charlotte", "biological", "transition", "preferences", "classification", "physician", "hollywood",
        "wikipedia", "spiritual", "photographs", "favourites", "relatively", "satisfaction", "represents", "preferred", "intellectual", "comfortable",
        "interaction", "listening", "effectively", "experimental", "revolution", "consolidation", "dependent", "mechanical", "consultants", "applicant",
        "cooperation", "acquisition", "implemented", "directories", "recognized", "notification", "licensing", "textbooks", "diversity", "cleveland",
        "investments", "accessibility", "sensitive", "templates", "completion", "universities", "technique", "contractors", "calculate", "alexander",
        "broadcast", "converted", "anniversary", "improvements", "specification", "accessible", "accessory", "representation", "arrangements", "conferences",
        "uniprotkb", "consumption", "birmingham", "afternoon", "consultant", "controller", "ownership", "committees", "legislative", "researchers",
        "molecular", "residence", "attorneys", "operators", "sustainable", "philippines", "statistical", "innovation", "employers", "definitions",
        "stainless", "newspapers", "exception", "successfully", "indonesia", "primarily", "capabilities", "recommendation", "recruitment", "organized",
        "improving", "expensive", "organisations", "explained", "programmes", "expertise", "mechanism", "jewellery", "eventually", "agreements",
        "considering", "innovative", "conclusion", "disorders", "collaboration", "detection", "formation", "engineers", "proposals", "moderator",
        "tutorials", "settlement", "collectables", "fantastic", "governments", "purchasing", "appointed", "operational", "corresponding", "descriptions",
        "determination", "animation", "productions", "telecommunications", "approaches", "designers", "scientists", "argentina", "possibility", "commissioner",
        "dangerous", "reliability", "unfortunately", "respectively", "volunteers", "attachment", "appointment", "hurricane", "represented", "mortgages",
        "responsibilities", "carefully", "productivity", "investors", "underground", "principle", "vacations", "calculated", "appearance", "incorporated",
        "notebooks", "valentine", "involving", "investing", "christopher", "admission", "situations", "allocated", "corrections", "structural",
        "municipal", "describes", "disabilities", "substance", "prohibited", "addressed", "simulation", "initiatives", "concentration", "interpretation",
        "optimization", "substances", "discovered", "restrictions", "participating", "exhibition", "composition", "nationwide", "definitely", "existence",
        "commentary", "limousines", "developments", "immigration", "destinations", "necessarily", "attribute", "apparently", "surrounding", "mountains",
        "popularity", "postposted", "coordinator", "obviously", "fundamental", "substantial", "progressive", "championship", "sacramento", "impossible",
        "testimonials", "memorabilia", "cartridge", "explanation", "cincinnati", "subsection", "electricity", "permitted", "confirmed", "wallpapers",
        "eligibility", "involvement", "placement", "observations", "vbulletin", "subsequent", "motorcycle", "disclosure", "establishment", "presentations",
        "undergraduate", "occupation", "donations", "associations", "citysearch", "radiation", "seriously", "elsewhere", "pollution", "conservative",
        "guestbook", "effectiveness", "atmosphere", "experiment", "purchases", "federation", "assignment", "chemicals", "everybody", "nashville",
        "counseling", "acceptable", "satisfied", "measurements", "milwaukee", "medication", "warehouse", "shareware", "violation", "configure",
        "stability", "southwest", "institutional", "expectations", "independence", "metabolism", "personally", "excellence", "somewhere", "attributes",
        "recognize", "screening", "forgotten", "behaviour", "intelligent", "edinburgh", "obligation", "regardless", "restricted", "attendance",
        "arguments", "amsterdam", "adventures", "announcement", "appreciate", "regularly", "mechanisms", "customize", "tradition", "indicators",
        "emissions", "physicians", "complaint", "experiments", "afghanistan", "scholarship", "governance", "supplements", "camcorder", "implementing",
        "ourselves", "conversation", "capability", "producing", "precision", "contributed", "reproduction", "ingredients", "franchise", "complaints",
        "promotions", "rehabilitation", "maintaining", "environments", "reception", "consequences", "geography", "appearing", "integrity", "discrimination",
        "processed", "implications", "functionality", "intermediate", "emotional", "overnight", "geographic", "preliminary", "introduce", "promotional",
        "specialists", "generator", "suspension", "correction", "authentication", "communicate", "supplement", "showtimes", "promoting", "machinery",
        "probability", "dimension", "schedules", "admissions", "quarterly", "illustrated", "continental", "alternate", "achievement", "limitations",
        "automated", "passenger", "convenient", "orientation", "childhood", "flexibility", "jurisdiction", "displaying", "encouraged", "cartridges",
        "declaration", "automation", "advantages", "preparing", "recipient", "extensions", "athletics", "southeast", "alternatives", "determining",
        "personalized", "conditioning", "partnerships", "destruction", "increasingly", "migration", "basically", "conventional", "applicants", "occupational",
        "adjustment", "treatments", "camcorders", "difficulty", "collective", "coalition", "enrollment", "producers", "collector", "interfaces",
        "advertisers", "representing", "observation", "restoration", "convenience", "returning", "opposition", "container", "defendant", "confirmation",
        "supervisor", "peripherals", "bestsellers", "departure", "minneapolis", "interactions", "intervention", "attraction", "modification", "customized",
        "understood", "assurance", "happening", "amendments", "metropolitan", "compilation", "verification", "attractive", "recordings", "jefferson",
        "gardening", "obligations", "orchestra", "polyphonic", "outsourcing", "adjustable", "allocation", "discipline", "identifying", "alphabetical",
        "dispatched", "installing", "voluntary", "photographer", "messaging", "additions", "requiring", "engagement", "refinance", "calendars",
        "arrangement", "conclusions", "bibliography", "compatibility", "furthermore", "cooperative", "measuring", "jacksonville", "headquarters", "transformation",
        "attachments", "administrators", "personality", "facilitate", "priorities", "bookstore", "parenting", "incredible", "commonwealth", "pharmaceutical",
        "manhattan", "workforce", "organizational", "portuguese", "everywhere", "discharge", "halloween", "hazardous", "methodology", "housewares",
        "reputation", "resistant", "qualifications", "slideshow", "variation", "transferred", "photograph", "distributor", "underlying", "gathering",
        "projection", "mathematical", "specialized", "diagnostic", "indianapolis", "corporations", "criticism", "automobile", "confidential", "statutory",
        "accommodations", "northeast", "downloaded", "paintings", "injection", "populations", "protective", "initially", "indicator", "eliminate",
        "sunglasses", "preference", "venezuela", "exploration", "sequences", "astronomy", "translate", "announces", "compression", "establishing",
        "constitutional", "submissions", "broadcasting", "horizontal", "informational", "ecommerce", "suffering", "prospective", "ultimately", "artificial",
        "spectacular", "coordination", "connector", "affiliated", "activation", "naturally", "mitsubishi", "underwear", "potentially", "inclusive",
        "dimensional", "considerable", "selecting", "processors", "pantyhose", "difficulties", "complexity", "barcelona", "documentary", "territories",
        "palestinian", "legislature", "hospitality", "procurement", "theoretical", "exercises", "surveillance", "protocols", "substitute", "inclusion",
        "hopefully", "brilliant", "evaluated", "assignments", "termination", "households", "authentic", "montgomery", "architectural", "louisville",
        "macintosh", "movements", "amenities", "virtually", "authorization", "projector", "comparative", "psychological", "surprised", "genealogy",
        "expenditure", "connectivity", "similarly", "collaborative", "excluding", "commander", "suggestion", "investigate", "connecting", "logistics",
        "proportion", "significance", "symposium", "essentials", "protecting", "transmitted", "screenshots", "intensive", "correspondence", "supervision",
        "expenditures", "separation", "testimony", "celebrities", "mandatory", "boundaries", "syndication", "celebration", "filtering", "offensive",
        "deployment", "colleagues", "separated", "directive", "governing", "retailers", "occasionally", "attending", "recruiting", "traveling",
        "preservation", "streaming", "intensity", "technological", "syndicate", "antivirus", "addressing", "discounted", "bangladesh", "constitute",
        "concluded", "desperate", "manufactured", "graduation", "variations", "addiction", "springfield", "undefined", "unemployment", "enhancement",
    };

    /// <summary>取指定难度档的单词池。</summary>
    /// <param name="difficulty">三档难度</param>
    /// <returns>该档的单词池</returns>
    public static IReadOnlyList<string> ForDifficulty(TypeMaster.Core.Enums.Difficulty difficulty)
        => difficulty switch
        {
            // 入门档复用简单档词表（3~5 字母的短词）。
            //
            // 为什么不单独准备一份更短的：3 字母已是英文实词的最短常见长度，
            // 再短就只有缩写词（如 IT / OK），练打字意义不大。
            // 入门档与简单档的差别体现在【单词长度上限与游戏节奏】上，
            // 见 TypingGameEngine.MaxWordLength 与 LoadParams。
            TypeMaster.Core.Enums.Difficulty.Entry => EasyWords,
            TypeMaster.Core.Enums.Difficulty.Easy => EasyWords,
            TypeMaster.Core.Enums.Difficulty.Normal => NormalWords,
            TypeMaster.Core.Enums.Difficulty.Hard => HardWords,
            // 地狱档复用困难档长词表（9+ 字母）；地狱感来自更快的节奏，词表已是最难
            TypeMaster.Core.Enums.Difficulty.Hell => HardWords,
            // 兜底不再落到最难的一档，避免将来新增档位时又是长词
            _ => EasyWords
        };
}
